# Generated by Django 5.2.1 on 2025-05-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='ordered_cities_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
